spring:
  datasource:
    url: jdbc:h2:file:/${user.dir}/database.h2
    driverClassName: org.h2.Driver
    username: sa
#    password: ...passed as environment variable or properties...
  h2:
    console:
      # The endpoint isn't secure, only good for development
      enabled: false
  jackson:
    serialization:
      indent_output: true

server:
  compression:
    enabled: true
  port: 8443
  ssl:
    enabled: true
    enabledProtocols: TLSv1.2
    keyAlias: localhost
    keyStore: classpath:keystore.p12
    keyStorePassword: changeit # Ideally password would be provided externally.
    keyStoreType: PKCS12

# Will do for the moment, plain simple
username: admin
#password: ...passed as environment variable or properties...

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure.security: INFO
    org.springframework.security: INFO


